### ISSUE TITLE
update access/delegate spec to use `nb: {delegations: Dict<string,Link>}` instead of `nb: Dict<string,Link>`

### ISSUE THREAD

**Issue by gobengo** [web3-storage/specs#45]
because the former is easier to type using ucanto atm. `nb` doesn't take a schema, so can't use `Schema.dictionary()` on it

**Comment by hugomrdias** [comment]
its `access/delegate` right ?

**Comment by gobengo** [comment]
@hugomrdias Yes, thank you!
