### ISSUE TITLE
"platform protocol": what happens when an added storage provider with a storage limit 'fills up' and someone wants to store more?

### ISSUE THREAD

**Issue by gobengo** [web3-storage/specs#9]
Scenario:

1. I create a space zSpace
2. I add a storage provider to the space `provider: "did:dns:free.web3.storage"`
    * note that this 'free' provider will only provide up to 5GiB of storage
3. I store 5 GiB of data in the space
4. I attempt to store 100MiB more data in the space. Ostensibly I am blocked because my storage provider doesn't allow this. It only allows up to 5GiB.
5. I decide I am willing to pay for a storage provider that will store more than 5GiB

What happens?
* Do I need to add a new storage provider that is not a 'free' one?
* Do I need to remove the 'free' storage provider?
  * If I have to remove my original storage provider, how can I feel confident that the data stored by that provider won't be lost and will still be stored by my new provider?
* Could there be something representing the agreement I make with a storage provider (e.g. a max cost or min service level) that I can update when I want to adjust the agreement (e.g. pay more)?
  * e.g. the provider would frequently be `web3.storage` but we could reify the 'provision' and e.g. have a property on it representing what exactly that provider had agreed to provide to the consumer (e.g. limitations, terms, price, etc)

**Comment by Gozala** [comment]
In this scenario you just add basic plan provider which replaces the free plan provider.

Providers will have a way to describe terms and how they compose so when you add it we can show them and get user consent including communicate these things

**Comment by Gozala** [comment]
In the future we’ll add support for providers that coexist as opposed to replace one another & a `store` field in `store/*` capabilities so you could specify which provider to store with.

In the meantime all our providers just replace / amend each other so we don’t have to deal with it in the initial version.

**Comment by gobengo** [comment]
ok I'm hearing that changing storage provider will be able to have some kind of 'this new storage provider *replaces* that old one', which provides semantics that help with my concern that a 'remove storage provider, then add a new one' process leaves some ambiguity around how the underlying data is maintained across storage providers.

It seems like a corollary of that is that if you try to replace a 10GiB storage provider with a 5GiB one, and you're storing 6GiB of data, we should either block that replacement, or at least issue a big warning that some of the stored data will no longer be guaranteed to be stored.

**Comment by Gozala** [comment]
> It seems like a corollary of that is that if you try to replace a 10GiB storage provider with a 5GiB one, and you're storing 6GiB of data, we should either block that replacement, or at least issue a big warning that some of the stored data will no longer be guaranteed to be stored.


Our current plans are effectively unlimited, downgrading plan just will charge you more for extra storage you use.

We will have to prevent going from payed plan to free if you’re storing more that what free plan gives you. Or perhaps block you from storing any extra data and we’ll email you a warning that we might erase your data unless you do delete what’s over quota or start paying instead.

This is a good question to ask @dchoi27 @jchris however.
